baseURL = "https://skanehira.github.io/blog/"
title = "ゴリラ@転生したら人間だった件"
defaultContentLanguage = "ja"
languageCode = "ja-jp"
disablePathToLower = true
hasCJKLanguage = true
pluralizeListTitles = false
pygmentsCodefences = true
theme = "basic-design-personal-blog"

[outputs]
    page = [ "HTML" , "AMP"  ]

[taxonomies]
    tag = "tags"

[permalinks]
    post = "/:section/:year/:month/:filename"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    lineNumbersInTable = true
    noClasses = true
    style = "solarized-dark"
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
    [[menu.global_header]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.global_header]]
        name = "Posts"
        url = "/posts"
        weight = 2
    [[menu.global_header]]
        name = "GitHub"
        url = "https://github.com/skanehira"
        weight = 3
    [[menu.global_header]]
        name = "Twitter"
        url = "https://twitter.com/gorilla0513"
        weight = 3

